collections:
  - name: https://github.com/stackhpc/ansible-collection-pulp
    version: api-update
    type: git
  - name: https://github.com/stackhpc/squeezer
    type: git
    version: rbac-utils
  - name: community.crypto
    version: 2.0.2
