collections:
  - name: https://github.com/stackhpc/ansible-collection-pulp
    type: git
    version: master
  # FIXME: Use a version once container support is released.
  - name: https://github.com/pulp/squeezer
    type: git
    version: develop
