collections:
  - name: https://github.com/stackhpc/ansible-collection-pulp
    type: git
    version: release-train
  # FIXME: Use a version once container support is released.
  - name: https://github.com/stackhpc/squeezer
    type: git
    version: rpm-sync-policy
