collections:
  - name: stackhpc.pulp
    version: 0.4.0
  # Pinned to git commit until new galaxy release
  - name: https://github.com/pulp/squeezer
    type: git
    version: d8c9f75d637abd1669ed8395e9dc86d3e0641d62
  - name: community.crypto
    version: 2.0.2
