---
- name: Check if working branch already exists on the remote
  ansible.builtin.shell:
    cmd: |
      gh api \
      -H "Accept: application/vnd.github.v3+json" \
      /repos/{{owner}}/{{repository_manifest.name}}/git/ref/heads/{{workflow_manifest.branch}}-workflows
  changed_when: false
  register: branch_exists
- name: Delete working branch from the remote
  ansible.builtin.shell:
    cmd: |
      gh api \
      --method DELETE \
      -H "Accept: application/vnd.github.v3+json" \
      /repos/{{owner}}/{{repository_manifest.name}}/git/refs/heads/{{workflow_manifest.branch}}-workflows
  when: branch_exists.rc == 0
- name: Create working branch
  ansible.builtin.shell:
    cmd: |
      git checkout -b {{workflow_manifest.branch}}-workflows \
        origin/{{workflow_manifest.prefix | default("")}}{{workflow_manifest.branch}}
    chdir: '{{staging_path}}/{{repository_manifest.name}}'
- name: Create .github/workflows directory
  ansible.builtin.file:
    path: '{{staging_path}}/{{repository_manifest.name}}/.github/workflows'
    state: directory
- name: Copy workflow into repository
  ansible.builtin.template:
    src: 'templates/{{workflow}}.jinja'
    dest: '{{staging_path}}/{{repository_manifest.name}}/.github/workflows/{{workflow}}.yml'
  with_items: '{{workflow_manifest.workflows}}'
  loop_control:
    loop_var: workflow
  register: workflow_copy
- name: Commit changes
  ansible.builtin.shell:
    cmd: "git add . && git commit -m 'feat: automatic update of workflows'"
    chdir: '{{staging_path}}/{{repository_manifest.name}}'
  when: workflow_copy.changed
- name: Push branch to remote
  ansible.builtin.shell:
    cmd: 'git push -u origin {{workflow_manifest.branch}}-workflows'
    chdir: '{{staging_path}}/{{repository_manifest.name}}'
  when: workflow_copy.changed
- name: Open pull request
  ansible.builtin.shell:
    cmd: 'gh pr create --fill --base {{workflow_manifest.prefix | default("")}}{{workflow_manifest.branch}}'
    chdir: '{{staging_path}}/{{repository_manifest.name}}'
  when: workflow_copy.changed
- name: Pause playbook to prevent exceeding API rate limit
  ansible.builtin.pause:
    seconds: 10
  when: workflow_copy.changed
