---
# This playbook queries the release Pulp server for the latest distribution of each
# repository. The version is extracted from the base_path, and used to generate
# a group_vars file containing repository versions for the client Pulp server.

- name: Update client repo versions
  hosts: localhost
  gather_facts: True
  vars:
    pulp_url: "{{ release_pulp_url }}"
    pulp_username: "{{ release_pulp_username }}"
    pulp_password: "{{ release_pulp_password }}"
  tasks:
    - name: Query repositories
      pulp.squeezer.rpm_repository:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_repos_list

    - name: Query publications
      pulp.squeezer.rpm_publication:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_pubs_list

    - name: Query distributions
      pulp.squeezer.rpm_distribution:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_dists_list

    - block:
        - name: Display latest distributions
          vars:
            info:
              repo: "{{ repo }}"
              pub: "{{ pub }}"
              dist: "{{ dist }}"
          debug:
            var: info
          loop: "{{ release_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"

        - name: Set a fact about latest versions
          vars:
            var_name: "{{ 'client_pulp_repo_' ~ item.short_name ~ '_version' }}"
            version: "{{ dist.base_path | basename }}"
          set_fact:
            latest_versions: "{{ latest_versions | default({}) | combine({var_name: version}) }}"
          loop: "{{ release_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"

        - name: Write latest versions to group_vars
          copy:
            content: |
              ---
              # Do not edit! This file is autogenerated by Ansible.
              {{ latest_versions | to_nice_yaml }}
            dest: "inventory/group_vars/all/client-pulp-repo-versions"
      vars:
        repo: "{{ pulp_repos_list.repositories | selectattr('name', 'equalto', item.repository) | first }}"
        pub: "{{ pulp_pubs_list.publications | selectattr('repository', 'equalto', repo.pulp_href) | sort(attribute='repository_version', reverse=True) | first }}"
        dist: "{{ pulp_dists_list.distributions | selectattr('publication', 'equalto', pub.pulp_href) | first }}"
