---
# This playbook queries the dev Pulp server for the latest distribution of each
# repository. The version is extracted from the base_path, and used to set the
# 'test_pulp_repository_rpm_repo_versions' fact which contains repository
# versions to sync to the test Pulp server.

- name: Update test repo versions
  hosts: localhost
  gather_facts: True
  vars:
    pulp_url: "{{ dev_pulp_url }}"
    pulp_username: "{{ dev_pulp_username }}"
    pulp_password: "{{ dev_pulp_password }}"
  tasks:
    - name: Query repositories
      pulp.squeezer.rpm_repository:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_repos_list

    - name: Query publications
      pulp.squeezer.rpm_publication:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_pubs_list

    - name: Query distributions
      pulp.squeezer.rpm_distribution:
        pulp_url: "{{ pulp_url }}"
        username: "{{ pulp_username }}"
        password: "{{ pulp_password }}"
      register: pulp_dists_list

    - block:
        - name: Display latest distributions
          vars:
            info:
              repo: "{{ repo }}"
              pub: "{{ pub }}"
              dist: "{{ dist }}"
          debug:
            var: info
          loop: "{{ dev_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"

        - name: Set a fact about latest versions
          set_fact:
            test_pulp_repository_rpm_repo_versions: "{{ test_pulp_repository_rpm_repo_versions | default({}) | combine({item.short_name: dist.base_path | basename}) }}"
          loop: "{{ dev_pulp_distribution_rpm }}"
          loop_control:
            label: "{{ item.repository }}"

        - name: Display latest versions fact
          debug:
            var: test_pulp_repository_rpm_repo_versions
      vars:
        repo: "{{ pulp_repos_list.repositories | selectattr('name', 'equalto', item.repository) | first }}"
        pub: "{{ pulp_pubs_list.publications | selectattr('repository', 'equalto', repo.pulp_href) | stackhpc.pulp.sort_publications | first }}"
        dist: "{{ pulp_dists_list.distributions | selectattr('publication', 'equalto', pub.pulp_href) | first }}"
