---
# This playbook generates a file containing Pulp repository versions for Kayobe.
# The version is taken from the current test versions.

- name: Update repository versions for Kayobe
  hosts: localhost
  gather_facts: True
  vars:
    kayobe_repository_versions_dest: "../pulp-repo-versions.yml"
  tasks:
    - name: Set a fact about test versions
      vars:
        kayobe_repository_versions_prefix: "stackhpc_pulp_repo_"
        kayobe_repository_versions_suffix: "_version"
        pulp_repository_versions_prefix: "test_pulp_repo_"
        pulp_repository_versions_suffix: "_version"
        kayobe_var_name: "{{ kayobe_repository_versions_prefix ~ item.short_name ~ kayobe_repository_versions_suffix }}"
        pulp_var_name: "{{ pulp_repository_versions_prefix ~ item.short_name ~ pulp_repository_versions_suffix }}"
        version: "{{ hostvars[inventory_hostname][pulp_var_name] }}"
      set_fact:
        test_versions: "{{ test_versions | default({}) | combine({kayobe_var_name: version}) }}"
      loop: "{{ test_pulp_distribution_rpm }}"
      loop_control:
        label: "{{ item.repository }}"

    - name: "Write test versions to {{ kayobe_repository_versions_dest }}"
      copy:
        content: |
          ---
          # Do not edit! This file is autogenerated by Ansible.
          {{ test_versions | to_nice_yaml }}
        dest: "{{ kayobe_repository_versions_dest }}"
