---
- name: Validate package repository configuration
  hosts: localhost
  gather_facts: true
  vars:
    published_rpm_package_repos: "{{ rpm_package_repos | selectattr('publish', 'defined') | selectattr('publish') | list + rpm_package_repos | rejectattr('publish', 'defined') | list }}"
    num_rpm_package_repos: "{{ rpm_package_repos | length }}"
    num_published_rpm_package_repos: "{{ published_rpm_package_repos | length }}"
  tasks:
    - name: Assert that RPM package repository list is defined
      assert:
        that:
          - rpm_package_repos is defined

    - name: Assert that RPM package repositories have names
      assert:
        that:
          - rpm_package_repos | rejectattr('name', 'defined') | list | length == 0

    - name: Assert that RPM package repository names are unique
      assert:
        that:
          - rpm_package_repos | map(attribute='name') | unique | list | length == num_rpm_package_repos | int

    - name: Assert that RPM package repositories have URLs
      assert:
        that:
          - rpm_package_repos | rejectattr('url', 'defined') | list | length == 0

    - name: Assert that published RPM package repositories have short names
      assert:
        that:
          - published_rpm_package_repos | rejectattr('short_name', 'defined') | list | length == 0

    - name: Assert that published RPM package repository short names are unique
      assert:
        that:
          - published_rpm_package_repos | map(attribute='short_name') | unique | list | length == num_published_rpm_package_repos | int

    - name: Assert that published RPM package repositories have base paths
      assert:
        that:
          - published_rpm_package_repos | rejectattr('base_path', 'defined') | list | length == 0

    - name: Assert that published RPM package repository base_paths are unique
      assert:
        that:
          - published_rpm_package_repos | map(attribute='base_path') | list | length == num_published_rpm_package_repos | int

    - name: Assert that dev package repository list is defined
      assert:
        that:
          - dev_pulp_repository_rpm_repos is defined

    - name: Assert that dev package publication list is defined
      assert:
        that:
          - dev_pulp_publication_rpm is defined

    - name: Assert that dev package distribution list is defined
      assert:
        that:
          - dev_pulp_distribution_rpm is defined

    - name: Assert that dev package distribution promote list is defined
      assert:
        that:
          - dev_pulp_distribution_rpm_promote is defined

    - name: Assert that test package repository list is defined
      assert:
        that:
          - test_pulp_repository_rpm_repos is defined

    - name: Assert that test package publication list is defined
      assert:
        that:
          - test_pulp_publication_rpm is defined

    - name: Assert that test package distribution list is defined
      assert:
        that:
          - test_pulp_distribution_rpm is defined
