---
name: Sync container repositories
on:
  workflow_dispatch:
    inputs:
      filter:
        description: Space-separated list of regular expressions matching images to sync
        type: string
        required: false
        default: ""
      distros:
        description: Space-separated list of base distributions to sync for
        type: string
        required: false
        default: ""

env:
  ANSIBLE_FORCE_COLOR: True
  ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/vault-pass
jobs:
  container-sync:
    name: Sync container repositories
    runs-on: [self-hosted, stackhpc-release-train]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Release Train & dependencies
      uses: ./.github/actions/setup
      with:
        vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        vault-password-file: ${{ env.ANSIBLE_VAULT_PASSWORD_FILE }}

    - name: Configure access control for stackhpc-dev namespace in Ark
      run: |
        ansible-playbook -i ansible/inventory \
        ansible/dev-pulp-container-publish.yml \
        -e kolla_container_image_filter="'$FILTER'" \
        -e kolla_base_distros_override="'$DISTROS'"
      env:
        FILTER: ${{ github.event.inputs.filter }}
        DISTROS: ${{ github.event.inputs.distros }}

    - name: Sync images in test with stackhpc-dev namespace in Ark
      run: |
        ansible-playbook -i ansible/inventory \
        ansible/test-pulp-container-sync.yml \
        -e kolla_container_image_filter="'$FILTER'" \
        -e kolla_base_distros_override="'$DISTROS'"
      env:
        FILTER: ${{ github.event.inputs.filter }}
        DISTROS: ${{ github.event.inputs.distros }}

    - name: Publish images in test
      run: |
        ansible-playbook -i ansible/inventory \
        ansible/test-pulp-container-publish.yml \
        -e kolla_container_image_filter="'$FILTER'" \
        -e kolla_base_distros_override="'$DISTROS'"
      env:
        FILTER: ${{ github.event.inputs.filter }}
        DISTROS: ${{ github.event.inputs.distros }}
