---
name: Promote container repositories
on:
  workflow_dispatch:

env:
  ANSIBLE_FORCE_COLOR: True
  ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/vault-pass
jobs:
  container-promote:
    runs-on: [self-hosted, stackhpc-release-train]
    steps:
    - uses: actions/checkout@master

    - name: Preparing Vault password file
      run: |
        echo "$ANSIBLE_VAULT_PASSWORD" > "$ANSIBLE_VAULT_PASSWORD_FILE"
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    - name: Installing dependencies
      run: |
        sudo apt update &&
        sudo apt install -y python3-venv &&
        python3 -m venv venv &&
        source venv/bin/activate &&
        pip install -U pip && 
        pip install -r requirements.txt &&
        ansible-galaxy collection install -r requirements.yml -p ansible/collections

    - name: Promote images from stackhpc-dev to stackhpc namespace in Ark
      run: |
        source venv/bin/activate &&
        ansible-playbook -i ansible/inventory \
        ansible/dev-pulp-container-promote.yml
