---
name: Publish container repositories
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/container-publish.yml'
      - 'ansible/dev-pulp-container-publish.yml'
      - 'ansible/inventory/group_vars/all/dev-pulp-containers'
      - 'ansible/inventory/group_vars/all/kolla'
  workflow_dispatch:
    inputs:
      filter:
        description: Space-separated list of regular expressions matching images to publish
        type: string
        required: false
        default: ""
      distros:
        description: Space-separated list of base distributions to publish
        type: string
        required: false
        default: ""
      skip_pulp:
        description: Whether to skip pulp promotion
        type: boolean
        default: true


env:
  ANSIBLE_FORCE_COLOR: True
  ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/vault-pass
jobs:
  container-publish:
    name: Publish container repositories
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Release Train & dependencies
      uses: ./.github/actions/setup
      with:
        vault-password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        vault-password-file: ${{ env.ANSIBLE_VAULT_PASSWORD_FILE }}

    - name: Publish container repositories
      run: |
        ansible-playbook -i ansible/inventory \
        ansible/dev-pulp-container-publish.yml \
        -e kolla_container_image_filter="'$FILTER'" \
        -e kolla_base_distros_override="'$DISTROS'"
      if: inputs.skip_pulp == false
      env:
        FILTER: ${{ github.event.inputs.filter }}
        DISTROS: ${{ github.event.inputs.distros }}
