---
name: Publish documentation
on:
  push:
    branches:
      - main
jobs:
  docs-publish:
    name: Publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs-requirements.txt
      - run: mkdocs gh-deploy --force
