---
name: Build documentation
on:
  pull_request:
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs-requirements.txt
      - run: mkdocs build

