---
name: Sync package repositories
on:
  workflow_dispatch:
    inputs:
      sync_ark:
        required: false
        description: Sync package repositories in Ark
        default: true
        type: boolean
      sync_test:
        required: false
        description: Sync package repositories in Test Pulp
        default: true
        type: boolean
      filter:
        description: Space-separated list of regular expressions matching short_name of repositories to sync
        type: string
        required: false
        default: ""
  schedule:
    # Daily at 02:17
    - cron: '17 2 * * *'

env:
  ANSIBLE_FORCE_COLOR: True
  ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/vault-pass
jobs:
  package-sync-ark:
    name: Sync package repositories in Ark
    runs-on: ubuntu-latest
    if: inputs.sync_ark || github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@master

    - name: Preparing Vault password file
      run: |
        echo "$ANSIBLE_VAULT_PASSWORD" > "$ANSIBLE_VAULT_PASSWORD_FILE"
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    - name: Installing dependencies
      run: |
        sudo apt update &&
        sudo apt install -y python3-venv &&
        python3 -m venv venv &&
        source venv/bin/activate &&
        pip install -U pip && 
        pip install -r requirements.txt &&
        ansible-galaxy collection install -r requirements.yml -p ansible/collections

    - name: Sync and publish package repositories in Ark
      run: |
        source venv/bin/activate &&
        ansible-playbook -i ansible/inventory \
        ansible/dev-pulp-repo-sync.yml \
        ansible/dev-pulp-repo-publication-cleanup.yml \
        ansible/dev-pulp-repo-publish.yml \
        -e deb_package_repo_filter="'$FILTER'" \
        -e rpm_package_repo_filter="'$FILTER'"
      env:
        FILTER: ${{ github.event.inputs.filter }}

  package-sync-test:
    name: Sync package repositories in test
    runs-on: [self-hosted, stackhpc-release-train]
    needs: package-sync-ark
    if: inputs.sync_test || github.event_name == 'schedule'
    steps:
    - uses: actions/checkout@master

    - name: Preparing Vault password file
      run: |
        echo "$ANSIBLE_VAULT_PASSWORD" > "$ANSIBLE_VAULT_PASSWORD_FILE"
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

    - name: Installing dependencies
      run: |
        sudo apt update &&
        sudo apt install -y python3-venv &&
        python3 -m venv venv &&
        source venv/bin/activate &&
        pip install -U pip && 
        pip install -r requirements.txt &&
        ansible-galaxy collection install -r requirements.yml -p ansible/collections

    - name: Sync and publish package repositories in test
      run: |
        source venv/bin/activate &&
        ansible-playbook -i ansible/inventory \
        ansible/test-pulp-repo-version-query.yml \
        ansible/test-pulp-repo-sync.yml \
        ansible/test-pulp-repo-publish.yml \
        -e deb_package_repo_filter="'$FILTER'" \
        -e rpm_package_repo_filter="'$FILTER'"
      env:
        FILTER: ${{ github.event.inputs.filter }}
