---
name: Synchronise Source Repositories
'on':
  push:
    branches: [main]
    paths:
      - '.github/workflows/source-repo-sync.yml'
      - 'ansible/inventory/group_vars/all/source-repositories'
      - 'ansible/roles/source-repo-sync/**'
      - 'ansible/source-repo-sync.yml'
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  source-repo-sync:
    runs-on: ubuntu-latest
    name: Synchronise source repositories
    steps:
      - name: Configure git 🔧
        run: |
          git config --global user.email "22933334+stackhpc-ci@users.noreply.github.com" &&
          git config --global user.name "stackhpc-ci"
      - name: Github checkout 🛎
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: 'false'
      - name: Run ansible playbook 📖
        run: ansible-playbook ansible/source-repo-sync.yml -i ansible/inventory
        env:
          ANSIBLE_FORCE_COLOR: True
          GITHUB_TOKEN: ${{secrets.repository_configuration_token}}
