---
name: Synchronise Repositories
'on':
  push:
    branches: [main]
    paths:
      - 'main.yml'
      - 'ansible.cfg'
      - 'inventory'
      - 'roles/**'
      - '.github/workflows/**'
permissions:
  contents: write
  pull-requests: write
env:
  GITHUB_TOKEN: ${{secrets.repository_configuration_token}}
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git 🔧
        run: |
          git config --global user.email "22933334+stackhpc-ci@users.noreply.github.com" &&
          git config --global user.name "stackhpc-ci"
      - name: Github checkout 🛎
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          persist-credentials: 'false'
      - name: Run ansible playbook 📖
        run: ansible-playbook main.yml
